### ISSUE TITLE
Costruire stazione di sviluppo

### ISSUE THREAD

**Issue by dortu-grassi** [itts-grassi-to/manageAccountSamba#4]
Scaricare dal seguente link la macchina virtuale server
https://drive.google.com/file/d/1RJiDrsl-d16onr8Oa-wXTVBKCdg_ejTj/view?usp=drive_link

user: info3
psw: ortu

**Comment by dortu-grassi** [comment]
Costruire una macchina virtuale con interfaccia grafica da mettere in rete con la macchina server

**Comment by gabrielharnagea** [comment]
fatto
